FROM openjdk:21-jdk-bullseye

WORKDIR /app

COPY build/libs/api-gateway-0.0.1-SNAPSHOT.jar /app/api-gateway.jar

EXPOSE 8080 5005

CMD ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "/app/api-gateway.jar"]