services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - produto-service
      - usuario-service

  produto-service:
    build:
      context: ./produtos
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - db

  usuario-service:
    build:
      context: ./usuario
      dockerfile: Dockerfile.dev
    ports:
      - "8082:8080"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgdata: