spring:
  cloud:
    gateway:
      routes:
        - id: produto-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/produtos/**
          filters:
            - StripPrefix=1
        - id: usuario-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/usuario/**
          filters:
            - StripPrefix=1