spring:
  cloud:
    gateway:
      routes:
        - id: produto-service
          uri: http://produto-service:8080/
          predicates:
          - Path=/api/produtos/**,/api/categorias/**
          filters:
          - StripPrefix=1
        - id: usuario-service
          uri: http://usuario-service:8080/
          predicates:
          - Path=/api/usuario/**
          filters:
          - StripPrefix=1
