FROM openjdk:21-jdk-bullseye

WORKDIR /app

COPY build/libs/service-discovery-0.0.1-SNAPSHOT.jar /app/service-discovery.jar

EXPOSE 8761 5005

CMD ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "/app/service-discovery.jar"]