FROM openjdk:21-jdk-bullseye

WORKDIR /app

COPY build/libs/crud-0.0.1-SNAPSHOT.jar /app/crud.jar

EXPOSE 8080 5005

CMD ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "/app/crud.jar"]